# -*- coding: utf-8 -*-

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

"""
Django settings for gourl_site project.

For more information on this file, see
https://docs.djangoproject.com/en/1.6/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.6/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
BASE_DIR = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.6/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tz2h2qi$q5#2h+*+&rgn+z=@_z=&%y%tyg@lty9x$s6u_r6g6v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TEMPLATE_DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

ROOT_URLCONF = 'gourl_site.urls'

WSGI_APPLICATION = 'gourl_wsgi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.6/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.6/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.6/howto/static-files/

STATIC_URL = '/static/'

###############################################################################
# GoUrl specific settings; everything above was automatically generated by
# django-admin.py and is left unmodified for easier migration to new versions
# of django
###############################################################################

TEMPLATE_CONTEXT_PROCESSORS = ()
TEMPLATE_DIRS = ()

# add GoUrl to the list of installed apps
INSTALLED_APPS += ("gourl",)

# templates that override the admin site
TEMPLATE_DIRS += (os.path.join(BASE_DIR, "gourl_site", "templates"),)

# enable the authentication middleware
TEMPLATE_CONTEXT_PROCESSORS += ("django.contrib.auth.context_processors.auth",)

# allow using CDNs or locally-served static versions of stuff
USE_CDNS = True
TEMPLATE_CONTEXT_PROCESSORS += ("gourl.context.use_cdns",)
